name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install gtest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C ${{ matrix.configuration }}
      
    - name: Install Prerequesites
      run: sudo apt-get update && sudo apt-get upgrade
    - name: More Prerequesites
      run: sudo apt-get -y install build-essential openssl libssl-dev libssl1.0 libgl1-mesa-dev libqt5x11extras5
      
    - name: Install Qt
  # You may pin to the exact commit or the version.
  # uses: jurplel/install-qt-action@2d518188e746defd451af981c3c901f463d99e29
      uses: jurplel/install-qt-action@v3.2.1
      with:
        # Directory to install Qt
        dir: '${{ github.workspace }}'
        # Version of Qt to install
        version: 6.4.3
        # Host platform
        host: linux
        # Target platform for build
        target: desktop
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
